CREATE TABLE HD_Customer(
    Customer_ID int GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    Customer_First_Name VARCHAR(20) NOT NULL,
    Customer_Last_Name VARCHAR(20) NOT NULL,
    Customer_FAVORITE_MEAL VARCHAR(20) NOT NULL
);
